### ISSUE TITLE
[BUG] An error occurred while hooking the system interface.

### ISSUE THREAD

**Issue by Ai686Leo** [DHD2280/Oxygen-Customizer#193]
### Describe the bug

Please refer to the screenshot, as I fear the translation may not be entirely accurate.

### Steps to reproduce

After hooking the system interface, select to restart the scope.
The system interface will continuously restart until the software detects an issue and voluntarily unhooks itself.
During the restart process, I observed that some of my adjusted options were implemented, yet the system persisted in restarting. After repeated restarts, a small portion of the system interface settings were also implemented.

### Expected behavior

Operating normally

### Screenshots

![Image](https://github.com/user-attachments/assets/55f75689-305e-4bd5-b4d8-f790a831b7e9)

### Device information

- Device: [OnePlus 11]
- OS: [ColorOS 16 with update 16.0.1.300]
- App version: [nightly-205 (#1842)(205)]

### Additional context

[oxygen_customizer.zip](https://github.com/user-attachments/files/24293796/oxygen_customizer.zip)

**Comment by DHD2280** [comment]
Hello.
I will slowly update the entire app to oos16 since I just received oos16 update (op11 EU).
As for now disable colored notifications if enabled.

**Comment by Ai686Leo** [comment]
> Hello.
> I will slowly update the entire app to oos16 since I just received oos16 update (op11 EU).
> As for now disable colored notifications if enabled.

ok

**Comment by DHD2280** [comment]
Hello
With latest few versions (nightly) crashes are fixed.
Notification style still bugged.

**Comment by Ai686Leo** [comment]
> Hello
> With latest few versions (nightly) crashes are fixed.
> Notification style still bugged.

@DHD2280 This issue remains unresolved.

**Comment by DHD2280** [comment]
> > Hello
> > With latest few versions (nightly) crashes are fixed.
> > Notification style still bugged.
> 
> [@DHD2280](https://github.com/DHD2280) This issue remains unresolved.

Then I need your lsposed logs

**Comment by Ai686Leo** [comment]
> > > Hello
> > > With latest few versions (nightly) crashes are fixed.
> > > Notification style still bugged.
> > 
> > [@DHD2280](https://github.com/DHD2280) This issue remains unresolved.
> 
> Then I need your lsposed logs

[log.zip](https://github.com/user-attachments/files/24365164/log.zip)
Here
nightly-205 (#1864)(205)

**Comment by DHD2280** [comment]
> [log.zip](https://github.com/user-attachments/files/24365164/log.zip) Here nightly-205 (#1864)(205)

Your issue is not caused by oc.
ColorOS Notify and/or lucky tool are crashing so oc thinks that systemui is bootlooped by its tweaks.
Disable one of them and check which is causing you issue.

**Comment by Ai686Leo** [comment]
> 
> > [log.zip](https://github.com/user-attachments/files/24365164/log.zip) Here nightly-205 (#1864)(205)
> 
> Your issue is not caused by oc.
> ColorOS Notify and/or lucky tool are crashing so oc thinks that systemui is bootlooped by its tweaks.
> Disable one of them and check which is causing you issue.

[log.zip](https://github.com/user-attachments/files/24369628/log.zip)

@DHD2280 is the log after disabling the two plugins that hooked into the system interface and restarting the system interface.

**Comment by DHD2280** [comment]
@Ai686Leo can you try [this](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20582004283)?

**Comment by Ai686Leo** [comment]
> @Ai686Leo can you try [this](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20582004283)?

[Log.zip](https://github.com/user-attachments/files/24375698/Log.zip)

No working

**Comment by DHD2280** [comment]
> > [@Ai686Leo](https://github.com/Ai686Leo) can you try [this](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20582004283)?
> 
> [Log.zip](https://github.com/user-attachments/files/24375698/Log.zip)
> 
> No working

Probably we fixed now
try [this](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20592262897)
I only need LSPosed logs

**Comment by Ai686Leo** [comment]
> > > [@Ai686Leo](https://github.com/Ai686Leo) can you try [this](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20582004283)?
> > 
> > [Log.zip](https://github.com/user-attachments/files/24375698/Log.zip)
> > 
> > No working
> 
> Probably we fixed now
> try [this](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20592262897)
> I only need LSPosed logs

[LSPosed_2025-12-30T16_47_19.416007.zip](https://github.com/user-attachments/files/24379555/LSPosed_2025-12-30T16_47_19.416007.zip)
It's still not working.
加油加油~  😁👍✊

**Comment by DHD2280** [comment]
> [LSPosed_2025-12-30T16_47_19.416007.zip](https://github.com/user-attachments/files/24379555/LSPosed_2025-12-30T16_47_19.416007.zip) It's still not working. 加油加油~ 😁👍✊

[Here we go](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20597362249)

**Comment by Ai686Leo** [comment]
> 
> > [LSPosed_2025-12-30T16_47_19.416007.zip](https://github.com/user-attachments/files/24379555/LSPosed_2025-12-30T16_47_19.416007.zip) It's still not working. 加油加油~ 😁👍✊
> 
> [Here we go](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20597362249)

It appears to have failed to build, and I'm unable to download it.🤔

**Comment by DHD2280** [comment]
> > > [LSPosed_2025-12-30T16_47_19.416007.zip](https://github.com/user-attachments/files/24379555/LSPosed_2025-12-30T16_47_19.416007.zip) It's still not working. 加油加油~ 😁👍✊
> > 
> > 
> > [Here we go](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/20597362249)
> 
> It appears to have failed to build, and I'm unable to download it.🤔

Try the new one coming

**Comment by Ai686Leo** [comment]
> Try the new one coming

[LSPosed_2025-12-30T22_29_58.899663.zip](https://github.com/user-attachments/files/24383603/LSPosed_2025-12-30T22_29_58.899663.zip)

Why on earth is that? (Is this translation accurate?) I have a significant block of free time tomorrow. If you still haven't found a solution, I could attempt mounting the ColorOS 16 system via dsu tomorrow afternoon (my time zone is UTC+8, and it's nearly 11pm now). Alternatively, you could provide the img files shown in the Oxygen OS image below. I'd like to help rule out whether the issue stems from other modules or plugins on my phone, or differences between the Chinese and international versions.
![Screenshot_2025-12-30-22-43-57-01_cdb399bbdd5ae3a3da2a11647bc61a18.jpg](https://github.com/user-attachments/assets/3a7e9be4-dc26-4db2-bf3d-1623a1b280f6)
I can offer my own private cloud storage if you happen to be short on cloud storage space.

**Comment by DHD2280** [comment]
> > Try the new one coming
> 
> [LSPosed_2025-12-30T22_29_58.899663.zip](https://github.com/user-attachments/files/24383603/LSPosed_2025-12-30T22_29_58.899663.zip)
> 
This time I don't see any error....
I don't know if tomorrow I can work on this
Please join in the telegram group and get in touch so we can check every build step-by-step faster

**Comment by Ai686Leo** [comment]
> Please join in the telegram group and get in touch so we can check every build step-by-step faster

I don't have Telegram...

**Comment by Ai686Leo** [comment]
> Please join in the telegram group and get in touch so we can check every build step-by-step faster

I'll try to register one.

**Comment by Ai686Leo** [comment]
> Please join in the telegram group and get in touch so we can check every build step-by-step faster

I only have two telephone numbers, one from mainland China and one from the Hong Kong Special Administrative Region, but it seems neither can be registered.

**Comment by Ai686Leo** [comment]
> Please join in the telegram group and get in touch so we can check every build step-by-step faster

I only have two telephone numbers, one from mainland China and one from the Hong Kong Special Administrative Region, but it seems neither can be registered.

**Comment by Ai686Leo** [comment]
> This time I don't see any error....

I tested the latest version within the dynamic system and found no issues; this problem should now be resolved. I can only investigate potential faults on my own device at this stage. Congratulations on fixing the bug.

**Comment by DHD2280** [comment]
Thank you for your time and your tests.

**Comment by Ai686Leo** [comment]
@DHD2280 Just now it occurred to me that this might be caused by a specific feature being incompatible. So I used the delete settings function and found the UI no longer rebooted. However, when I restored the settings (using the bin file function) and closed as many open features as possible, it still rebooted.

This is the bin file after disabling as many features as possible. Please take a look, as I simply cannot pinpoint the issue, and I'm rather keen to get some sleep.😓

[OxygenCustomizer_Config.zip](https://github.com/user-attachments/files/24476446/OxygenCustomizer_Config.zip)

**Comment by DHD2280** [comment]
@Ai686Leo 
I was busy
If you still have the issue provide a crashlog with logfox or any app 
It will register the systemui crash

**Comment by Ai686Leo** [comment]
> @Ai686Leo 
> I was busy
> If you still have the issue provide a crashlog with logfox or any app 
> It will register the systemui crash

After clearing the settings, I manually reconfigured them as before and it did not crash. I suspect the previous version may have encountered issues when saving settings, resulting in a corrupted configuration file. However, this should now be fixed, so I have closed this issue as unplanned.
Do take care to rest properly.   :-)
