### ISSUE TITLE
[BUG] Fingerprint icon stays on after enabling custom icon

### ISSUE THREAD

**Issue by Leny1337** [DHD2280/Oxygen-Customizer#63]
### Describe the bug

After I enable custom fingerprint icon on lockscreen settings, it is always visible even when AOD is in energy saving mode and screen turns off, fingerprint icon is still visible. It's hiding when I hide front camera only.

### Steps to reproduce

1. Go to Lockscreen->Custom ingerprint Icon
2. Turn off screen
3. Fingerprint icon is still visible

### Expected behavior

Fingerprint icon should dissapear after a while.

### Device information

- Device: OnePlus 12
- OS: Oxygen OS 14 with update 840
- App version: [V1.1.1-Beta](https://github.com/DHD2280/Oxygen-Customizer/releases/tag/V1.1.1-Beta)

**Comment by Leny1337** [comment]
Okay, maybe it's a false-positive, because my cat was walking near my phone and I've noticed that fingerprint icon is showing itself after "change" on front camera is detected (like pocket detection)... 🐈

**Comment by DHD2280** [comment]
Hello.
Kindly switch to nightly, this bug was fixed time ago.
Unfortunately I haven't had time to make a new beta, even a new stable, since I keep pushing features 😅

**Comment by Leny1337** [comment]
@DHD2280 it works fine now on nightly, thanks!

**Comment by Leny1337** [comment]
@DHD2280 Looks like I've found another bug regarding fingerprint icon and this bug is still visible on latest nightly-11.

I've enabled smart lock with my smartwatch. After some time, fingerprint icon appears on the screen (and nothing else), looks like after some time without using the phone - smart lock is turning on the locking again, which causes fingerprint to be visible and disappear only after I pick up the phone, unlock and lock again.

**Comment by DHD2280** [comment]
> @DHD2280 Looks like I've found another bug regarding fingerprint icon and this bug is still visible on latest nightly-11.
> 
> I've enabled smart lock with my smartwatch. After some time, fingerprint icon appears on the screen (and nothing else), looks like after some time without using the phone - smart lock is turning on the locking again, which causes fingerprint to be visible and disappear only after I pick up the phone, unlock and lock again. 

This behaviour isn't related to Oxygen Customizer.
In settings you can choose if you keep the fingerprint icon visible in AOD or not.

**Comment by Leny1337** [comment]
> This behaviour isn't related to Oxygen Customizer.
> In settings you can choose if you keep the fingerprint icon visible in AOD or not.

I've checked, when I disable custom icon on Oxygen Customizer, everything is fine. After I enable custom icon and disconnect my smartwatch, fingerprint icon shows and nothing else. No clock, just black screen with fingerprint icon. 

Edit: Okay, it looks like it may be a bug with OxygenOS...

**Comment by DHD2280** [comment]
> Edit: Okay, it looks like it may be a bug with OxygenOS...

Check if same behaviour happens with all lsposed modules off and let me know.

**Comment by Leny1337** [comment]
I have disabled fingerprint visibility on AOD and now it's fine (don't need it tbh), so I will close the issue.
