### ISSUE TITLE
[FEATURE] Add support for OOS 15

### ISSUE THREAD

**Issue by zmeyerNTC** [DHD2280/Oxygen-Customizer#81]
### Describe the feature

Falls to install on oos 15

### Why would it be useful to add?

Support

### Example(s)

Add support for oos15

**Comment by DHD2280** [comment]
Hello.
Unfortunately I haven't got OOS15 yet.
Also without any log I can't help you.

As for now some tweaks are still working on OOS15, just uncheck framework in LSPosed.

**Comment by gridan17** [comment]
+1.
It happens after upgrade OP12 to A15.
The last version doesn't allow to start zygisk at all. 
What makes impossible to use any lsposed module and some magisk modules too.
Please fix it!

**Comment by DHD2280** [comment]
> +1.
> It happens after upgrade OP12 to A15.
> The last version doesn't allow to start zygisk at all. 
> What makes impossible to use any lsposed module and some magisk modules too.
> Please fix it!

Try JingMatrix or Irena lsposed.
If you want to try OC on OOS15, uncheck framework in lsposed.

**Comment by soundgirl101** [comment]
Overall most features set in beta-11 are working in OOS 15, framework is unchecked! OP 12 Magisk 28! Fabulous work!

**Comment by gridan17** [comment]
> Overall most features set in beta-11 are working in OOS 15!

Lucky you!
Almost all settings that I used on A14, doesn't work without lsposed on A15. Neither stable nor beta 11.

**Comment by DHD2280** [comment]
> > Overall most features set in beta-11 are working in OOS 15!
> 
> Lucky you! Almost all settings that I used on A14, doesn't work without lsposed on A15. Neither stable nor beta 11.

Which features?
Are you using nighties?

**Comment by dan4ik605743** [comment]
I can't do it. I use the nightly build, I disable the framework in lspsoed, after rebooting the system gets into a bootloop

**Comment by repinek** [comment]
The nightly builds work quite well, except for the lockscreen and the AOD tab, where some features work buggy and some not at all (custom clock, weather, widgets, and other things). Tested on GT Neo 5 (Realme ui 6, .320 patch, CN)
Thank you for this incredible module!

**Comment by repinek** [comment]
> > > Overall most features set in beta-11 are working in OOS 15!
> > 
> > 
> > Lucky you! Almost all settings that I used on A14, doesn't work without lsposed on A15. Neither stable nor beta 11.
> 
> Which features? Are you using nighties?

The nightly builds (I used 201, #1052) work quite well, except for the lockscreen and the AOD tab, where some features work buggy and some not at all (custom clock, weather, widgets, and other things). Tested on GT Neo 5 (Realme ui 6, .320 patch, CN)
Thank you for this incredible module!

**Comment by repinek** [comment]
> > > > Overall most features set in beta-11 are working in OOS 15!
> > > 
> > > 
> > > Lucky you! Almost all settings that I used on A14, doesn't work without lsposed on A15. Neither stable nor beta 11.
> > 
> > Which features? Are you using nighties?
> 
> The nightly builds (I used 201, #1052) work quite well, except for the lockscreen and the AOD tab, where some features work buggy and some not at all (custom clock, weather, widgets, and other things). Tested on GT Neo 5 (Realme ui 6, .320 patch, CN)
> Thank you for this incredible module!

![Screenshot_2024-12-27-23-26-17-85_cdb399bbdd5ae3a3da2a11647bc61a18.jpg](https://github.com/user-attachments/assets/a68a26e1-4596-4dcd-92fa-5fbb258483ca)

also, this annoying bug, forgot to say about it

**Comment by DHD2280** [comment]
> > > > Overall most features set in beta-11 are working in OOS 15!
> > > 
> > > 
> > > Lucky you! Almost all settings that I used on A14, doesn't work without lsposed on A15. Neither stable nor beta 11.
> > 
> > 
> > Which features? Are you using nighties?
> 
> The nightly builds (I used 201, #1052) work quite well, except for the lockscreen and the AOD tab, where some features work buggy and some not at all (custom clock, weather, widgets, and other things). Tested on GT Neo 5 (Realme ui 6, .320 patch, CN) Thank you for this incredible module!

I just got oos15 yesterday, so expect more updates for oos15

**Comment by repinek** [comment]
> > > > > Overall most features set in beta-11 are working in OOS 15!
> > > > 
> > > > 
> > > > Lucky you! Almost all settings that I used on A14, doesn't work without lsposed on A15. Neither stable nor beta 11.
> > > 
> > > 
> > > Which features? Are you using nighties?
> > 
> > 
> > The nightly builds (I used 201, #1052) work quite well, except for the lockscreen and the AOD tab, where some features work buggy and some not at all (custom clock, weather, widgets, and other things). Tested on GT Neo 5 (Realme ui 6, .320 patch, CN) Thank you for this incredible module!
> 
> I just got oos15 yesterday, so expect more updates for oos15

Thank you! Waiting for a new release, because settings are not saving properly

**Comment by DHD2280** [comment]
Hello.

News for oos15:
- QS widgets done
- Lockscreen stuff done (Todo: improve animations)

TODO:
- fix media player with qs widgets off,
- qs tile colors

**Comment by crick-ru** [comment]
> Hello.
> 
> News for oos15:
> 
> * QS widgets done
> * Lockscreen stuff done (Todo: improve animations)
> 
> TODO:
> 
> * fix media player with qs widgets off,
> * qs tile colors

Hello. Thank you for your excellent work! In nightly builds, almost everything works. But the lock icon does not clear on the lockscreen.

**Comment by DHD2280** [comment]
> Hello.
> 
> News for oos15:
> - QS widgets done
> - Lockscreen stuff done (Todo: improve animations)
> 
> TODO:
> - fix media player with qs widgets off,
> - qs tile colors

Qs media player also fixed with commit
be83f47fe5d3ba03e8483c762caa4af70d2e691b
Lockscreen stuff now fully working too.

**Comment by crick-ru** [comment]
> Lockscreen stuff now fully working too.

Sorry, but the lock icon still won't clear.

![Image](https://github.com/user-attachments/assets/3d5860ad-0187-43dd-ac84-b75793621621)

![Image](https://github.com/user-attachments/assets/bf3b036c-d28d-4655-bb18-2500d5a64a63)
