### ISSUE TITLE
[BUG] System UI status "Causes bootloop" in OC.

### ISSUE THREAD

**Issue by oofkodkskkskkks** [DHD2280/Oxygen-Customizer#93]
### Describe the bug

Everytime I reboot my device, it works fine for about 5 minutes with all the customisation plugins, until it randomly starts to constantly soft crash, (where I don't lose my progress, however it keeps going black and crashing) and after that most customisations by oxygen customizer are gone such as lock screen customisation.
![Screenshot_2024-11-28-13-36-21-28_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/bad5fec7-e79d-4346-a17d-3facf10ac5c3)

### Steps to reproduce

Enable the lock screen customisation 

### Expected behavior

I expected it to normally work, and for all my plugins to work correctly

### Device information

- Device: [OnePlus Nord 2T 5G]
- OS: [Oxygen OS 14 with update 14.0.0.607 EX01]
- App version: [e.g. v2.0.1]

**Comment by DHD2280** [comment]
Please attach lsposed logs.

**Comment by oofkodkskkskkks** [comment]
[Uploading LSPosed_2024-11-28T15_07_03.952445.zip…]()

**Comment by DHD2280** [comment]
> Uploading LSPosed_2024-11-28T15_07_03.952445.zip…

Please wait the upload and attach again, this is not valid.

**Comment by oofkodkskkskkks** [comment]
[LSPosedLogs.zip](https://github.com/user-attachments/files/17952407/LSPosedLogs.zip)

**Comment by DHD2280** [comment]
> [LSPosedLogs.zip](https://github.com/user-attachments/files/17952407/LSPosedLogs.zip)

Disable aod customziations.
Try latest nightly available in GitHub actions and check again.
Those I see in logs seems cos errors.
Enable more logging in settings (after installing latest nightly), enable aod customziations and send fresh logs.

**Comment by oofkodkskkskkks** [comment]
Thank you, that worked 🙏

**Comment by DHD2280** [comment]
> Thank you, that worked 🙏

But I want to go deeper into this issue:
Issue fixed in nightly?
If not, does this happen with aod clock or aod weather?
Thank you

**Comment by oofkodkskkskkks** [comment]
So actually, this issue was fixed in non nightly after disabling aod clock, I never had the weather on. However after going to nightly, it actually broke again, even without them on.
![Screenshot_2024-11-29-02-05-26-19_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/f7f4f92f-221e-4807-b2c3-f909f3605dc8)
[LSPosed_2024-11-29T02_08_09.132645.zip](https://github.com/user-attachments/files/17952986/LSPosed_2024-11-29T02_08_09.132645.zip)

**Comment by DHD2280** [comment]
> So actually, this issue was fixed in non nightly after disabling aod clock, I never had the weather on. However after going to nightly, it actually broke again, even without them on. ![Screenshot_2024-11-29-02-05-26-19_cdb399bbdd5ae3a3da2a11647bc61a18](https://private-user-images.githubusercontent.com/67191139/390926328-f7f4f92f-221e-4807-b2c3-f909f3605dc8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI4MzkzODcsIm5iZiI6MTczMjgzOTA4NywicGF0aCI6Ii82NzE5MTEzOS8zOTA5MjYzMjgtZjdmNGY5MmYtMjIxZS00ODA3LWIyYzMtZjkwOWYzNjA1ZGM4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI5VDAwMTEyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1ODJlNTg3NzVlYmU3MjNiNDJjYzM0NzkwMGI4ZjZjNDMyNTY5NDE1OGUyMmJhMmZiNzc4OTg2ZjNkNTJlYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uNH-H-ZTp_HlcQs80CdWAVUEOCD8y9rmmQ9pka8f4h4) [LSPosed_2024-11-29T02_08_09.132645.zip](https://github.com/user-attachments/files/17952986/LSPosed_2024-11-29T02_08_09.132645.zip)

Did you do a full reboot after installing latest nightly?
I can still see in logs version 2.0.1

**Comment by oofkodkskkskkks** [comment]
Well, that's embarrassing. Completely forgot to reboot, my bad. That fixed
the hooks. Will try to see if aod options are fixed.

**Comment by oofkodkskkskkks** [comment]
[LSPosed_2024-11-29T02_18_32.508969.zip](https://github.com/user-attachments/files/17953030/LSPosed_2024-11-29T02_18_32.508969.zip)
Would appear that it isn't fixed on nightly, nearly as soon as I put on the AOD clock customisation, my phone crashed about 5 times, and ended up without half the customisations again.
![Screenshot_2024-11-29-02-19-46-18_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/2c8d2cc2-fc59-4520-a47e-f7f450a6282f)

**Comment by DHD2280** [comment]
> Would appear that it isn't fixed on nightly, nearly as soon as I put on the AOD clock customisation, my phone crashed about 5 times, and ended up without half the customisations again. !

You are on beta!
Use this [version](https://github.com/DHD2280/Oxygen-Customizer/actions/runs/12077171572), reboot and check again

**Comment by oofkodkskkskkks** [comment]
Apologies, GitHub is confusing for me. Couldn't find the specific nightly
build so I assumed that it was under beta. Will try nightly once I get home.

**Comment by oofkodkskkskkks** [comment]
[LSPosed_2024-11-30T18_53_41.488904.zip](https://github.com/user-attachments/files/17966159/LSPosed_2024-11-30T18_53_41.488904.zip)
![Screenshot_2024-11-30-18-54-29-24_cdb399bbdd5ae3a3da2a11647bc61a18](https://github.com/user-attachments/assets/7f219b25-560d-485e-8be0-7d818b0b6734)

**Comment by DHD2280** [comment]
> [LSPosed_2024-11-30T18_53_41.488904.zip](https://github.com/user-attachments/files/17966159/LSPosed_2024-11-30T18_53_41.488904.zip)

Do you have any aod mod enabled?
Aod clock, aod weather or depth subject in aod?

**Comment by oofkodkskkskkks** [comment]
Only AOD clock.

**Comment by DHD2280** [comment]
> Only AOD clock.

Can you show your AOD Clock settings from stock settings?
Try to set default clock.

**Comment by DHD2280** [comment]
> > Only AOD clock.
> 
> Can you show your AOD Clock settings from stock settings?
> Try to set default clock.
> 

![Screenshot_2024-12-05-09-20-03-05_e4c56ca12ff849ac0a9dbc8dae07f3aa.jpg](https://github.com/user-attachments/assets/01f5225a-40ba-45f7-a51b-171c884dff47)

Like this one
@oofkodkskkskkks

**Comment by DHD2280** [comment]
Aod Clock must be set to stock value when customizing from customizer.
